### ISSUE TITLE
AP_Periph feature requests / idea tracking

### ISSUE THREAD

**Issue by pkocmoud** [ArduPilot/ardupilot#12617]
This issue is for keeping track of and discussion of feature requests specifically for the AP_Periph UAVCAN firmware. 

The era of available CAN devices is here, lets get creative!

- [ ] Enable hardware CAN message filtering

- [ ] Test the ability of the CANNode to handle an extreme number of messages before and after enabling hardware CAN message filtering

- [ ] Discussion and implementation of CAN LED status messages. Focus on keeping the superfluous to a minimum.

- [ ] Discussion and implementation of one device duplicate Auto Node Allocation mitigation.

- [ ] Create Firmware to enable the CANNode to be a standalone UART to CAN converter.

- [ ] CAN telemetry support of UART based radios.

- [ ] Enable the onboard CAN rail voltage sensing, logging, and error reporting. (Pin PB8)

- [ ] Stub support for 2 ADC inputs (Pins PB0, PB1).

- [ ] Stub support for 3 GP IOs (Pins PC13, PC14, PC15) as switch inputs or digital outputs?

- [ ] Prepare support for STM32F303CCT chip.

- [ ] CAN to PWM, sBUS support?

- [ ] RCinput to CAN?

Any other ideas?

**Comment by tridge** [comment]
good list, thanks!
