### ISSUE TITLE
Improvement to Obstacle Avoidance GSOC Goals

### ISSUE THREAD

**Issue by rishabsingh3003** [ArduPilot/ardupilot#14405]
I am consolidating the list of already opened issues that I will be working on for this year's Google Summer of Code. It will be easy to track my progress from here, and I will link all my PR's here.  It would also be nice to receive any advice on how I could approach these.
The following five issues will be the first on my to-do list:

- [x] https://github.com/ArduPilot/ardupilot/issues/13215: BendyRuler and Object Database should work in 3D (Fixed in: https://github.com/ArduPilot/ardupilot/pull/14556) 

- [x] Provide option to search for clear paths vertically in BendyRuler, instead of just horizontally (Fixed in: https://github.com/ArduPilot/ardupilot/pull/14726)

- [x] https://github.com/ArduPilot/ardupilot/issues/11961: Resolve BendyRuler's hesitancy (Fixed in: https://github.com/ArduPilot/ardupilot/pull/14595)

- [x] https://github.com/ArduPilot/ardupilot/issues/11565: Recovery from BendyRuler avoidance may impact the fence (Fixed in https://github.com/ArduPilot/ardupilot/pull/14422)

- [x] https://github.com/ArduPilot/ardupilot/issues/7706:  Vehicles should back away from objects in normal Avoidance (Fixed in: https://github.com/ArduPilot/ardupilot/pull/14819)

- [x] https://github.com/ArduPilot/ardupilot/issues/11562: Add proximity sensor support to Dijkstra's
       A better solution to solve this issue seems to be Running Dijkstra's with BendyRuler (Fixed in: https://github.com/ArduPilot/ardupilot/pull/14934)

The Spline WP methods are being changed, therefore this issue will only be dealt with after the Spline changes are finalized: 
- [ ] https://github.com/ArduPilot/ardupilot/issues/12691: Dijkstra's should work with Spline waypoints

Any changes to the current plan will be updated here.

**Comment by rishabsingh3003** [comment]
I am including  other minor improvements/ Bug fixes made to Avoidance or related so we can have a summary of all the changes that were made in this short period:
1. Reject obstacles near home (easier autonomous takeoff's) - https://github.com/ArduPilot/ardupilot/pull/15136
2. Bug fix with "Stop mode" never reaching the desired margin - https://github.com/ArduPilot/ardupilot/pull/14817
3. Check if readings are valid before sending it down to OA DB - https://github.com/ArduPilot/ardupilot/pull/14793
4. Check if origin is set before running OA- https://github.com/ArduPilot/ardupilot/pull/14607
5. Log simple avoidance as "SA" messages (As part of backing away PR)

**Comment by rmackay9** [comment]
I think we can close this now 'cuz this successful GSoC project has completed, thanks!
