### ISSUE TITLE
ChibiOS: Missing Features

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#8109]
This is a summary of known regressions and reported bugs in the move to ChibiOS

- [x] Analog stop pins for sonars ( dev team has decided not to support this under chibios as it's obscure) (Removed in #12195)
- [ ] FMUv1 support ( dev team has decided not to support this under chibios initially as very old and rare hardware )
- [ ] aerofc-v1 support
- [x] VRBrain support
- [x] APJ does not include the appropriate git hash entries
- [x] Board voltage arming checks are disabled. (Fixed in #9714)

Issues reported in Copter-3.6 beta testing thread:
- [x] Oreo LEDs for Solo not working ([issue](https://github.com/ArduPilot/ardupilot/issues/9076))
- [x] Solo gimbal twitch ([issue](https://github.com/ArduPilot/ardupilot/issues/9181))
- [x] dshot beeping or motors start/stop ([discussion](https://discuss.ardupilot.org/t/copter-3-6-0-rc6-available-for-beta-testing/30943/4))

Issues reported for plane:
 - [x] possible I2C issue https://discuss.ardupilot.org/t/plane-3-9-2-stable-release/33873/26

non code issues:
- [x] get eclipse+waf working together for windows builds so we can retire make soon too .
- [ ] update documentation in wiki to remove all PX4 and/orNuttx references, especially dev build howtos.

**Comment by davidbuzz** [comment]
I'd say this list is short enough, and the issues obscure enough that we can just put these into the release document as known incomplete, and ship chibios without them.

**Comment by DavidIngraham** [comment]
A few others I've found while bringing up the F405-Wing:
- OSD Support (This would be an enhancement, but we have it in the F4Light HAL)
- SPI SD Card Support (This is common on lower end boards)
- Detection of all external i2c compasses

**Comment by Naterater** [comment]
As of the last dev call, it was mentioned that shutter feedback was not yet active on ChibiOS. Has that been addressed?

**Comment by WickedShell** [comment]
@Naterater #8886 would resolve it

**Comment by tridge** [comment]
@DavidIngraham we have now implemented osd support, spi sd card support and external compasses on all boards

**Comment by hdtechk** [comment]
Support for OreoLED is not on list and not working

**Comment by EShamaev** [comment]
https://github.com/ArduPilot/ardupilot/pull/9285

<=FMUv3 DSM receiver binding

**Comment by Gregmaan** [comment]
Hi i am using a Pixhawk 1 and would like to use the ADC inputs (RSSI, Airspeed). Are there any plans to support these inputs.
Or should I buy another board and i2c airspeed sensor?
Regards
Gregor

**Comment by palm369** [comment]
Just tested 3.9.2 and RPM input on aux pin is not working. But it is checked as done here. What is the status?

**Comment by tridge** [comment]
@palm369 my guess is you have not set BRD_PWM_COUNT correctly (its a common mistake)

**Comment by davidbuzz** [comment]
see also here: https://github.com/ArduPilot/ardupilot/pull/9651

**Comment by palm369** [comment]
@tridge RPM is only working with the NuttX firmware version, but not working on ChibiOS. I just double checked it with AP3.9.3 B1.

**Comment by peterbarker** [comment]
On Tue, 6 Nov 2018, David Kaden wrote:

> @tridge RPM is only working with the NuttX firmware version, but not working
> on ChibiOS. I just double checked it with AP3.9.3 B1.

Which board and pin?

**Comment by tridge** [comment]
@palm369 the most likely reason is you have BRD_PWM_COUNT setup so that the pin is assigned to PWM, not GPIO. On PX4 the conflict wasn't detected, but with ChibiOS we enforce this

**Comment by palm369** [comment]
Cube, AUX5, BRD_PWM_COUNT=4 in both cases

**Comment by peterbarker** [comment]
On Tue, 6 Nov 2018, David Kaden wrote:

> Cube, AUX5, BRD_PWM_COUNT=4 in both cases

Hmmm.

Could you put a copy of your parameters (or a dataflash log) up somewhere, 
please?

**Comment by palm369** [comment]
@peterbarker https://www.dropbox.com/s/qfjp4mijeqqb9w2/latest%20params.param?dl=0

**Comment by WickedShell** [comment]
@tridge ChibiOS isn't setting the `ardupilot_git_hash` key in the apj, and is leaving the git field from px4 as not filled out. Also depends upon `PX4Firmware/Tools/px_mkfw.py` which would need to be replaced before PX4Firmware could be removed.

**Comment by peterbarker** [comment]
On Wed, 7 Nov 2018, David Kaden wrote:

> @peterbarker https://www.dropbox.com/s/qfjp4mijeqqb9w2/latest%20params.param?dl=0

Please try setting RELAY_PIN to -1

**Comment by Pedals2Paddles** [comment]
Can the Solo's LED driver be ported over before the Nuttx builds are killed?

**Comment by proficnc** [comment]
Whoops sorry

**Comment by palm369** [comment]
@peterbarker > Please try setting RELAY_PIN to -1

That solved it, thanks. But I have not ever touched this param, it must been set automatically while upgrading to chibiOS. Shouldn't be that way IMHO

**Comment by Pedals2Paddles** [comment]
Added https://github.com/ArduPilot/ardupilot/issues/9763 for the simulated DSM not working on the new IO.

**Comment by Pedals2Paddles** [comment]
DSM fixed in https://github.com/ArduPilot/ardupilot/pull/9786

**Comment by bchristal** [comment]
Thought I'd add to the list. Hot shoe events are not recognized by 3.9.3 Chibios. Hot shoe events work fine in 3.9.3 standard.

**Comment by Naterater** [comment]
Check your BRD_PWM_COUNT and make sure that your aux channels aren’t PWM. NuttX didn’t enforce that parameter correctly. I have both trig and Cam events running master.

On Nov 30, 2018, at 14:36, Brian Christal <notifications@github.com<mailto:notifications@github.com>> wrote:


Thought I'd add to the list. Hot shoe events are not recognized by 3.9.3 Chibios. Hot shoe events work fine in 3.9.3 standard.

**Comment by bchristal** [comment]
Hi Nathan,

Thanks. I think you're right, but I'm not clear on using BRD_PWM_COUNT. The default setting is 4. I assumed AUX 1-4 were PWM, AUX 5-6 General Purpose? Moving the hot shoe cable to AUX 6 (PIN 55) works. So I set BRD_PWM_COUNT to 3 (assuming AUX 1-3 are PWM and 4-6 are General Purpose) and connected the the Hot Shoe cable to Pin 53, AUX4 (Fast capture), but it is not recognized.

Do you know how BRD_PWM_COUNT affects the AUX pins?

Brian

**Comment by Naterater** [comment]
@WickedShell, I see 3 items on the list that are related to the missing features that haven't been completed yet:

- [ ] aerofc-v1 support
- [ ] VRBrain support
- [ ] APJ does not include the appropriate git hash entries

Is that right? I think the wiki is a separate issue not related to missing features, and the items that are decidedly unsupported shouldn't hold up closing this issue. Maybe those could be separated into separate issues?

**Comment by TimothyGold** [comment]
I tried ChiBiOS with the latest ArduCopter on PixRacer yesterday and found that Analog RSSI is not implemented.  Everything else seems to work as far as I could tell.

**Comment by Zadrob** [comment]
ChibiOS SRXL protocol support for new Spektrum receivers.
They have just changed CRC. (from AR7700 to AR9030)

**Comment by kd0aij** [comment]
It looks like we lost this functionality when moving to ChibiOS: ArduPilot/PX4Firmware#38
